### ISSUE TITLE
Avoid including unused/duplicate vertices in output

### ISSUE THREAD

**Issue by mfsch** [HaoxuanGuo/MeshBridge.jl#12]
If `mesh.position` contains duplicate vertices, the current implementation produces a `SimpleMesh` that contains multiple copies of the same vertex in the points list, only some of which are used in the connectivity list. This can lead to some [weird behavior](https://github.com/JuliaGeometry/Meshes.jl/issues/306) and is a bit wasteful. I’ve posted a simplified implementation [here](https://github.com/JuliaIO/MeshIO.jl/issues/67#issuecomment-1268931642) that doesn’t have this issue, in case you want to change this in MeshBridge.jl.

**Comment by hx-guo** [comment]
@mfsch Thank you for your advice. I merged your code into the library.
